"""Constants relevant to ast code."""

import ast
from typed_ast import ast27
from typed_ast import ast3

NODE_TYPE_TO_TOKENS = {
    ast27.Add: ('+',),
    ast27.And: ('and',),
    ast27.BitAnd: ('&',),
    ast27.BitOr: ('|',),
    ast27.BitXor: ('^',),
    ast27.Div: ('/',),
    ast27.Eq: ('==',),
    ast27.FloorDiv: ('//',),
    ast27.Gt: ('>',),
    ast27.GtE: ('>=',),
    ast27.In: ('in',),
    ast27.Invert: ('~',),
    ast27.Is: ('is',),
    ast27.IsNot: (
        'is',
        'not',
    ),
    ast27.LShift: ('<<',),
    ast27.Lt: ('<',),
    ast27.LtE: ('<=',),
    ast27.Mod: ('%',),
    ast27.Mult: ('*',),
    ast27.Not: ('not',),
    ast27.NotEq: ('!=',),
    ast27.NotIn: (
        'not',
        'in',
    ),
    ast27.Or: ('or',),
    ast27.Pow: ('**',),
    ast27.RShift: ('>>',),
    ast27.Sub: ('-',),
    ast27.UAdd: ('+',),
    ast27.USub: ('-',),
    ast3.Add: ('+',),
    ast3.And: ('and',),
    ast3.BitAnd: ('&',),
    ast3.BitOr: ('|',),
    ast3.BitXor: ('^',),
    ast3.Div: ('/',),
    ast3.Eq: ('==',),
    ast3.FloorDiv: ('//',),
    ast3.Gt: ('>',),
    ast3.GtE: ('>=',),
    ast3.In: ('in',),
    ast3.Invert: ('~',),
    ast3.Is: ('is',),
    ast3.IsNot: (
        'is',
        'not',
    ),
    ast3.LShift: ('<<',),
    ast3.Lt: ('<',),
    ast3.LtE: ('<=',),
    ast3.Mod: ('%',),
    ast3.Mult: ('*',),
    ast3.Not: ('not',),
    ast3.NotEq: ('!=',),
    ast3.NotIn: (
        'not',
        'in',
    ),
    ast3.Or: ('or',),
    ast3.Pow: ('**',),
    ast3.RShift: ('>>',),
    ast3.Sub: ('-',),
    ast3.UAdd: ('+',),
    ast3.USub: ('-',),
    ast3.MatMult: ('@',),
}
